### ISSUE TITLE
Failing Download on DCP

### ISSUE THREAD

**Issue by roshanyadav29** [hitansh1299/IITB_LCS#9]
The Option to upload and view those files is working. But the Download Files Options are failing for all of the current database. Please Check. I have attached a Screenshot for your reference.

![issue_dcp](https://github.com/hitansh1299/IITB_LCS/assets/56498395/52555b70-15e6-4945-9969-cf3df1c76ec0)

**Comment by hitansh1299** [comment]
File download is fixed now. Issue in OS level semantics, resolved in latest change (Forward and backslash)
